name: Deploy Website

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::728092359661:role/frontend-github-actions-role
          aws-region: eu-west-2
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - name: Install playwright (for mermaid.js)
        run: pnpm exec playwright install
      - name: Build website
        run: pnpm build
      - name: Deploy to S3
        run: aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"

permissions:
  id-token: write
  contents: read